export const cartData = [{
    "id": "1",
    "product": "Historical",
    "image": "images/historicalbooks/img1.jpg",
    "title": "Guns, Germs, and Steel",
    "author": "Jared M. Diamond",
    "price": "299",
    "category": "Historical",
    "description": "Why did Eurasians conquer, displace, or decimate Native Americans, Australians, and Africans, instead of the reverse? In this groundbreaking book, evolutionary biologist Jared Diamond stunningly dismantles racially based theories of human history by revealing the environmental factors actually responsible for history's broadest patterns. Here, at last, is a world history that really is a history of all the world's peoples, a unified narrative of human life even more intriguing and important than accounts of dinosaurs and glaciers.",
    "publishDate": "1997",
    "publisher": "W.W. Norton",
    "language": "English",
    "subjects": "Social Science, Anthropology, General",
},
{
    "id": "2",
    "product": "Historical",
    "image": "images/historicalbooks/img2.jpg",
    "title": "Hindus in Hindu Rashtra",
    "author": " Anand Ranganathan",
    "price": "399",
    "category": "Historical",
    "description": "This book depicts how Hinduism/Hindus have been subjected to discrimination and constant injustice under the garb of Secularism and how Hindus are being reduced to a Eighth Class Citizens in their own land. He had taken 8 chapters to expose the bigotry of our system.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "3",
    "product": "Historical",
    "image": "images/historicalbooks/img3.jpg",
    "title": "India: A History",
    "author": "  John Keay ",
    "price": "399",
    "category": "Historical",
    "description": "TA comprehensive survey of India's history from ancient times to the present.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "4",
    "product": "Historical",
    "image": "images/historicalbooks/img4.jpg",
    "title": "The Wonder That Was India",
    "author": "A.L. Basham",
    "price": "399",
    "category": "Historical",
    "description": "A classic work that explores the cultural history of India, covering religion, society, and philosophy.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "5",
    "product": "Historical",
    "image": "images/historicalbooks/img5.jpg",
    "title": "A Study of History",
    "author": "Arnold J. Toynbee",
    "price": "399",
    "category": "Historical",
    "description": "This book depicts how Hinduism/Hindus have been subjected to discrimination and constant injustice under the garb of Secularism and how Hindus are being reduced to a Eighth Class Citizens in their own land. He had taken 8 chapters to expose the bigotry of our system.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "6",
    "product": "Historical",
    "image": "images/historicalbooks/img6.png",
    "title": "The Rise and Fall of the Third Reich",
    "author": "William L. Shirer",
    "price": "399",
    "category": "Historical",
    "description": "This book depicts how Hinduism/Hindus have been subjected to discrimination and constant injustice under the garb of Secularism and how Hindus are being reduced to a Eighth Class Citizens in their own land. He had taken 8 chapters to expose the bigotry of our system.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "7",
    "product": "Historical",
    "image": "images/historicalbooks/img7.jpg",
    "title": "The Origins of Totalitarianism",
    "author": "Hannah Arendt",
    "price": "399",
    "category": "Historical",
    "description": "This book depicts how Hinduism/Hindus have been subjected to discrimination and constant injustice under the garb of Secularism and how Hindus are being reduced to a Eighth Class Citizens in their own land. He had taken 8 chapters to expose the bigotry of our system.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "8",
    "product": "Historical",
    "image": "images/historicalbooks/img8.jpg",
    "title": "The Gulag Archipelago",
    "author": "Aleksandr Solzhenitsyn",
    "price": "399",
    "category": "Historical",
    "description": "This book depicts how Hinduism/Hindus have been subjected to discrimination and constant injustice under the garb of Secularism and how Hindus are being reduced to a Eighth Class Citizens in their own land. He had taken 8 chapters to expose the bigotry of our system.",
    "publishDate": "2023",
    "publisher": "BluePrint/BluOne Ink LLP",
    "language": "English",
    "subjects": "History, Asia, General",
},
{
    "id": "9",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img1.jpg",
    "title": "The Giving Tree",
    "author": "Shel Silverstein",
    "price": "299",
    "category": "Children",
    "description": "The book follows the lives of an apple tree and a boy, who develop a relationship with each other. The tree is very giving and the boy ages into a taking teenager, a young man, a middle-aged man, and finally an elderly man. Despite the fact that the boy ages in the story, the tree addresses the boy as Boy throughout his entire life.",
    "publishDate": "October 7, 1964",
    "publisher": "Harper & Row",
    "language": "English",
    "subjects": "Children's picture book",
},
{
    "id": "10",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img2.jpg",
    "title": "Good Night Moon",
    "author": "	Margaret Wise Brown",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "11",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img3.jpg",
    "title": "Charlotte's Web",
    "author": "E.B. White",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "12",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img4.jpg",
    "title": "The Harry Potter series",
    "author": " J.K. Rowling",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "13",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img5.jpg",
    "title": "Alice's Adventure in Wonderland",
    "author": "Lewis Carroll",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "14",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img6.jpg",
    "title": "The Chronicles of Narnia series",
    "author": "C.S. Lewis",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "15",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img7.jpg",
    "title": "Where the Wild Things Are",
    "author": "Maurice Sendak ",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "16",
    "product": "Children Literature",
    "image": "images/childrenliteraturebooks/img8.jpg",
    "title": "The Tale of Peter Rabbit",
    "author": "Beatrix Potter",
    "price": "399",
    "category": "Children",
    "description": "Goodnight Moon is an American children's book written by Margaret Wise Brown and illustrated by Clement Hurd. It was published on September 3, 1947, and is a highly acclaimed bedtime story.",
    "publishDate": "September 3, 1947",
    "publisher": "Harper & Brothers",
    "language": "English",
    "subjects": "Children's literature",
},
{
    "id": "17",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img1.jpg",
    "title": "The Power",
    "author": "	Naomi Alderman",
    "price": "299",
    "category": "Dystopian",
    "description": "The Power is a 2016 science fiction novel by the British writer Naomi Alderman.[1] Its central premise is of women developing the ability to release electrical jolts from their fingers, which allows them to become the dominant sex. In 2017, it won the Baileys Women's Prize for Fiction.",
    "publishDate": "2016",
    "publisher": "Viking",
    "language": "English",
    "subjects": "Dystopian/Science fiction",
},
{
    "id": "18",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img2.jpg",
    "title": "We",
    "author": "	Yevgeny Zamyatin",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "19",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img3.jpg",
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "20",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img4.jpg",
    "title": "The Handmaid's Tale",
    "author": "Margaret Atwood",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "21",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img5.jpg",
    "title": "A Clockwork Orange ",
    "author": " Anthony Burgess",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "22",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img6.jpg",
    "title": "Do Androids Dream of Electric Sheep? ",
    "author": "Philip K. Dick",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "23",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img7.jpg",
    "title": "The Road",
    "author": "Cormac McCarthy",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "24",
    "product": "Dystopian",
    "image": "images/dystopianbooks/img8.jpg",
    "title": "The Children of Men",
    "author": "P.D. James",
    "price": "369",
    "category": "Dystopian",
    "description": "The novel describes a world of harmony and conformity within a united totalitarian state. It influenced the emergence of dystopia as a literary genre. George Orwell said that Aldous Huxley's 1931 Brave New World must be partly derived from We, although Huxley denied this. ",
    "publishDate": "1924",
    "publisher": "E. P. Dutton",
    "language": "Russian",
    "subjects": "Dystopian novel, science fiction",
},
{
    "id": "25",
    "product": "Fantasy",
    "image": "images/fantasybooks/img1.jpg",
    "title": "The Library at Mount Char",
    "author": "Scott Hawkins",
    "price": "299",
    "category": "Fiction/Fantasy",
    "description": "Carolyn had lived with eleven siblings under the care of a millennia-old and godlike man known to them as Father (also known as Ablakha or Adam Black), prone to acts of sadistic cruelty.",
    "publishDate": "2015",
    "publisher": "Crown Books",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "26",
    "product": "Fantasy",
    "image": "images/fantasybooks/img2.jpg",
    "title": "Sorcery of Thorns",
    "author": "Margaret Rogerson",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "27",
    "product": "Fantasy",
    "image": "images/fantasybooks/img3.jpg",
    "title": "The Wheel of Time series",
    "author": "Robert Jordan",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "28",
    "product": "Fantasy",
    "image": "images/fantasybooks/img4.jpg",
    "title": "American Gods",
    "author": "Neil Gaiman",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "29",
    "product": "Fantasy",
    "image": "images/fantasybooks/img5.jpg",
    "title": "Mistborn trilogy",
    "author": "Brandon Sanderson",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "30",
    "product": "Fantasy",
    "image": "images/fantasybooks/img6.jpg",
    "title": "The Name of the Wind",
    "author": "Patrick Rothfuss",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "31",
    "product": "Fantasy",
    "image": "images/fantasybooks/img7.jpg",
    "title": "A Song of Ice and Fire series",
    "author": "George R.R. Martin",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "32",
    "product": "Fantasy",
    "image": "images/fantasybooks/img8.jpg",
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "price": "269",
    "category": "Fantasy/ Romance",
    "description": "Elisabeth has known that for as long as she can remember. Raised in one of Austermeer’s Great Libraries, Elisabeth has grown up among magical grimoires that, if provoked, transform into grotesque monsters of ink and leather. When the library’s most dangerous grimoire is released, Elisabeth is blamed. With no one to turn to but her sworn enemy, the sorcerer Nathaniel Thorn, she finds herself entangled in a centuries-old conspiracy.",
    "publishDate": "2022",
    "publisher": "Simon and Schuster",
    "language": "English",
    "subjects": "Fantasy, horror",
},
{
    "id": "33",
    "product": "Fiction",
    "image": "images/fictionbooks/img1.jpg",
    "title": "The Goldfinch",
    "author": "Donna Tartt",
    "price": "299",
    "category": "Fiction",
    "description": "The Goldfinch tells the story of Theo Decker, a young boy who survives an explosion at a museum that kills his mother. In the chaos, he steals a famous painting called The Goldfinch, which becomes a symbol of hope and a connection to his lost past as he navigates a life marked by loss, love, and crime.",
    "publishDate": "October 22, 2013",
    "publisher": "Little, Brown and Company",
    "language": "English",
    "subjects": "Literary Fiction, Drama, Coming-of-Age",
},
{
    "id": "34",
    "product": "Fiction",
    "image": "images/fictionbooks/img2.jpg",
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},
{
    "id": "35",
    "product": "Fiction",
    "image": "images/fictionbooks/img3.jpg",
    "title": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},{
    "id": "36",
    "product": "Fiction",
    "image": "images/fictionbooks/img4.jpg",
    "title": "Invisible Man",
    "author": "Ralph Ellison",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},{
    "id": "37",
    "product": "Fiction",
    "image": "images/fictionbooks/img5.jpg",
    "title": "Middlemarch",
    "author": "George Eliot",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},{
    "id": "38",
    "product": "Fiction",
    "image": "images/fictionbooks/img6.jpg",
    "title": "The Grapes of Wrath",
    "author": " John Steinbeck",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},
{
    "id": "39",
    "product": "Fiction",
    "image": "images/fictionbooks/img7.jpg",
    "title": "Slaughterhouse-Five",
    "author": "Kurt Vonnegut",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},
{
    "id": "40",
    "product": "Fiction",
    "image": "images/fictionbooks/img8.jpg",
    "title": "Wuthering Heights",
    "author": " Emily Brontë",
    "price": "269",
    "category": "Fiction",
    "description": "To Kill a Mockingbird is a Pulitzer Prize-winning novel set in the 1930s American South. It follows Scout Finch, a young girl whose father, Atticus Finch, is a lawyer defending a Black man accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and empathy.",
    "publishDate": "July 11, 1960",
    "publisher": "J.B. Lippincott & Co.",
    "language": "English",
    "subjects": "Literary Fiction, Social Issues, Historical Fiction",
},
{
    "id": "41",
    "product": "Mystery",
    "image": "images/mysterybooks/img1.jpg",
    "title": "Witch Way to Murder",
    "author": "Shirley Damsgaard",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "42",
    "product": "Mystery",
    "image": "images/mysterybooks/img2.jpg",
    "title": "The Nature of Disappearing",
    "author": "Kimi Cunningham Grant",
    "price": "369",
    "category": "Mystery",
    "description": "In this captivating novel of suspense, a wilderness guide must team up with the man who ruined her life years ago when the friend who introduced them goes missing. Emlyn doesn’t let herself think about the past.",
    "publishDate": "June 18, 2024",
    "publisher": "Minotaur Books",
    "language": "English",
    "subjects": "Thriller, Mystery, Mystery Thriller, Fiction, Suspense, Adult",
},
{
    "id": "43",
    "product": "Mystery",
    "image": "images/mysterybooks/img3.jpg",
    "title": "The Big Sleep",
    "author": "Raymond Chandler",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "44",
    "product": "Mystery",
    "image": "images/mysterybooks/img4.jpg",
    "title": "In Cold Blood",
    "author": "Truman Capot",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "45",
    "product": "Mystery",
    "image": "images/mysterybooks/img5.jpg",
    "title": "Gone Girl",
    "author": " Gillian Flynn",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "46",
    "product": "Mystery",
    "image": "images/mysterybooks/img6.jpg",
    "title": "The Hound of the Baskervilles",
    "author": "Arthur Conan Doyle ",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "47",
    "product": "Mystery",
    "image": "images/mysterybooks/img7.jpg",
    "title": "The Maltese Falcon",
    "author": "Dashiell Hammett",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "48",
    "product": "Mystery",
    "image": "images/mysterybooks/img8.jpg",
    "title": "And Then There Were None",
    "author": "Agatha Christie",
    "price": "299",
    "category": "Mystery",
    "description": "Bewitched meets Murder She Wrote in this delightful new cozy mystery series featuring Ophelia Jensen, small town librarian and reluctant psychic, and her grandmother Abby, a benevolent witch.",
    "publishDate": "August 30, 2005",
    "publisher": "Avon",
    "language": "English",
    "subjects": "Mystery, Paranormal, Witches, Cozy Mystery",
},
{
    "id": "49",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img1.jpg",
    "title": "Dune",
    "author": "Frank Herbert",
    "price": "389",
    "category": "Science Fiction",
    "description": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...",
    "publishDate": "June 1, 1965",
    "publisher": "Ace",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "50",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img2.jpg",
    "title": "The Hunger Games",
    "author": "Suzanne Collins",
    "price": "399",
    "category": "Science Fiction",
    "description": "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "51",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img3.jpg",
    "title": "The War of the Worlds",
    "author": "H.G. Wells",
    "price": "399",
    "category": "Science Fiction",
    "description": "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "52",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img4.jpg",
    "title": "Foundation",
    "author": "Isaac Asimov",
    "price": "399",
    "category": "Science Fiction",
    "description": "The first book in Asimov's series exploring the future of humanity through psychohistory.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},{
    "id": "53",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img5.jpg",
    "title": "Neuromancer",
    "author": "William Gibson",
    "price": "399",
    "category": "Science Fiction",
    "description": "A seminal cyberpunk novel about hacking and artificial intelligence.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "54",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img6.jpg",
    "title": "1984",
    "author": "George Orwell",
    "price": "399",
    "category": "Science Fiction",
    "description": "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "55",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img7.jpg",
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "price": "399",
    "category": "Science Fiction",
    "description": "Depicts a futuristic society where technology, conditioning, and social order reign supreme.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "56",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img8.jpg",
    "title": "The Dispossessed",
    "author": "Ursula K. Le Guin",
    "price": "399",
    "category": "Science Fiction",
    "description": "Explores political ideologies through the story of an anarchist society and its neighboring capitalist one.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "57",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img9.jpg",
    "title": "Dan Simmons",
    "author": "Aldous Huxley",
    "price": "399",
    "category": "Science Fiction",
    "description": "The first book in a series, known for its complex narrative structure and exploration of AI and humanity.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "58",
    "product": "Fantasy",
    "image": "images/sciencefictionbooks/img10.jpg",
    "title": "Snow Crash",
    "author": "Neal Stephenson",
    "price": "399",
    "category": "Science Fiction",
    "description": "A fast-paced cyberpunk novel blending virtual reality, linguistics, and corporate control.",
    "publishDate": "October 14, 2008",
    "publisher": "Scholastic Press",
    "language": "English",
    "subjects": "Science Fiction, Fiction, Fantasy",
},
{
    "id": "59",
    "product": "Thriller",
    "image": "images/thrillerbooks/img1.jpg",
    "title": "Incidents Around the House",
    "author": "Josh Malerman",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},
{
    "id": "60",
    "product": "Thriller",
    "image": "images/thrillerbooks/img2.jpg",
    "title": "Two Sides to Every Murder",
    "author": "Danielle Valentine",
    "price": "369",
    "category": "Thriller",
    "description": "From the author of How to Survive Your Murder comes a propulsive thriller about two teens who return to the site of the famous murder case that sealed their fates.",
    "publishDate": "June 25, 2024",
    "publisher": "G.P. Putnam's Sons Books for Young Readers",
    "language": "English",
    "subjects": "Mystery,Young Adult,Thriller,Murder Mystery",
},
{
    "id": "61",
    "product": "Thriller",
    "image": "images/thrillerbooks/img3.jpg",
    "title": "The Silence of the Lambs",
    "author": "Thomas Harris",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},,
{
    "id": "62",
    "product": "Thriller",
    "image": "images/thrillerbooks/img4.jpg",
    "title": "The Girl on the Train",
    "author": "Paula Hawkins",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},,
{
    "id": "63",
    "product": "Thriller",
    "image": "images/thrillerbooks/img5.jpg",
    "title": "Shutter Island",
    "author": "Dennis Lehane",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},,
{
    "id": "64",
    "product": "Thriller",
    "image": "images/thrillerbooks/img6.jpg",
    "title": "Sharp Objects",
    "author": "Gillian Flynn",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},,
{
    "id": "65",
    "product": "Thriller",
    "image": "images/thrillerbooks/img7.jpg",
    "title": "Before I Go to Sleep",
    "author": "S.J. Watson",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},,
{
    "id": "66",
    "product": "Thriller",
    "image": "images/thrillerbooks/img8.jpg",
    "title": "Big Little Lies",
    "author": "Liane Moriarty",
    "price": "299",
    "category": "Thriller",
    "description": "To eight-year-old Bela, her family is her world. There is Mommy, Daddo, and Grandma Ruth. But there is also Other Mommy, a malevolent entity who asks her every day: Can I go inside your heart?",
    "publishDate": "June 25, 2024",
    "publisher": "Del Rey",
    "language": "English",
    "subjects": "Horror,Fiction,Paranormal,Thriller,Adult",
},
{
    "id": "67",
    "product": "Award Winners",
    "image": "images/awardwinnerbooks/img1.jpg",
    "title": "The Night Circus",
    "author": "Erin Morgenstern",
    "price": "299",
    "category": "Fantasy",
    "description": "This enchanting novel follows the story of a magical competition between two young illusionists, Celia and Marco, who fall in love despite the stakes of their rivalry.",
    "publishDate": "September 13, 2011",
    "publisher": " Doubleday",
    "language": "English",
    "subjects": "Fantasy, Romance, Magical Realism",
    "Awards":"Locus Award for Best First Novel (2012)",
},
{
    "id": "68",
    "product": "Award Winners",
    "image": "images/awardwinnerbooks/img2.jpg",
    "title": "The Underground Railroad",
    "author": "Colson Whitehead",
    "price": "369",
    "category": "Historical",
    "description": "A Pulitzer Prize-winning novel that reimagines the historical Underground Railroad as a literal train system, exploring themes of slavery and freedom through the journey of Cora, a young enslaved woman.",
    "publishDate": "September 13, 2016",
    "publisher": "Doubleday",
    "language": "English",
    "subjects": "Historical Fiction, Social Issues",
    "Awards":"Pulitzer Prize for Fiction (2017), National Book Award for Fiction (2016)",
},
{
    "id": "69",
    "product": "Award Winners",
    "image": "images/awardwinnerbooks/img3.jpg",
    "title": "Where the Crawdads Sing",
    "author": "Delia Owens",
    "price": "369",
    "category": "Mystery & Thriller",
    "description": "This bestselling novel combines a coming-of-age story with a mystery, focusing on Kya Clark, the Marsh Girl, as she grows up in the swamps of North Carolina and becomes entangled in a local murder investigation.",
    "publishDate": "August 14, 2018",
    "publisher": "G.P. Putnam’s Sons",
    "language": "English",
    "subjects": "Mystery, Thriller, Literary Fiction",
    "Awards":"Goodreads Choice Award for Fiction (2018), Southern Book Prize (2020)",
},
{
    "id": "70",
    "product": "Award Winners",
    "image": "images/awardwinnerbooks/img4.jpg",
    "title": "The Overstory",
    "author": "Richard Powers",
    "price": "369",
    "category": "Fiction",
    "description": "This Pulitzer Prize-winning novel tells the interconnected stories of several characters whose lives are deeply intertwined with the life cycles of trees and the environment, exploring themes of ecology and activism.",
    "publishDate": "September 26, 2018",
    "publisher": "W.W. Norton & Company",
    "language": "English",
    "subjects": "Romance, Contemporary Fiction",
    "Awards":"Pulitzer Prize for Fiction (2019), National Book Award Finalist (2018)",
},
{
    "id": "71",
    "product": "Award Winners",
    "image": "images/awardwinnerbooks/img5.jpg",
    "title": "A Man Called Ove",
    "author": "Fredrik Backman",
    "price": "369",
    "category": "Fiction",
    "description": "A heartwarming novel about Ove, a grumpy yet lovable man whose life changes when new neighbors move in and slowly help him rediscover joy and purpose.",
    "publishDate": "August 31, 2012 ",
    "publisher": "Original - Forum (Sweden), English - Atria Books",
    "language": "Swedish (Original), English (Translation)",
    "subjects": "Contemporary Fiction, Humor, Drama",
    "Awards":"Goodreads Choice Award for Fiction (2014), Swedish Book of the Year (2013)",
},
{
    "id": "72",
    "product": "Best Sellers",
    "image": "images/bestsellerbooks/img1.jpg",
    "title": "Fourth Wing",
    "author": "Rebecca Yarros",
    "price": "299",
    "category": "Fiction",
    "description": "Set in the lorem jgfjh hug hufy huf ghdrsuytivv tdrdiuyg fytdutfiuygfoyug disastrous loves, and crushing losses.",
    "publishDate": "May 2, 2023",
    "publisher": "Red Tower Books",
    "language": "English",
    "subjects": "Fantasy, Romance",
},
{
    "id": "73",
    "product": "Best Sellers",
    "image": "images/bestsellerbooks/img2.jpg",
    "title": "The Wishing Game",
    "author": "Meg Shaffer",
    "price": "369",
    "category": "Children",
    "description": "Set in the lorem jgfjh hug hufy huf ghdrsuytivv tdrdiuyg fytdutfiuygfoyug disastrous loves, and crushing losses.",
    "publishDate": "June 29, 2021",
    "publisher": "Dial Books",
    "language": "English",
    "subjects": "Fantasy, Middle-Grade Fiction",
},
{
    "id": "74",
    "product": "Best Sellers",
    "image": "images/bestsellerbooks/img3.jpg",
    "title": "The Last Devil to Die",
    "author": "Richard Osman",
    "price": "369",
    "category": "Mystery & Thriller",
    "description": "Set in the lorem jgfjh hug hufy huf ghdrsuytivv tdrdiuyg fytdutfiuygfoyug disastrous loves, and crushing losses.",
    "publishDate": "September 19, 2023",
    "publisher": "Viking",
    "language": "English",
    "subjects": "Crime Fiction, Mystery",
},
{
    "id": "75",
    "product": "Best Sellers",
    "image": "images/bestsellerbooks/img4.jpg",
    "title": "It Ends with Us",
    "author": "Colleen Hoover",
    "price": "369",
    "category": "Fiction",
    "description": "Set in the lorem jgfjh hug hufy huf ghdrsuytivv tdrdiuyg fytdutfiuygfoyug disastrous loves, and crushing losses.",
    "publishDate": "August 2, 2016",
    "publisher": "Atria Books",
    "language": "English",
    "subjects": "Romance, Contemporary Fiction",
},
{
    "id": "76",
    "product": "Best Sellers",
    "image": "images/bestsellerbooks/img5.jpg",
    "title": "Demon Copperhead",
    "author": "Barbara Kingsolver",
    "price": "369",
    "category": "Fiction",
    "description": "Set in the lorem jgfjh hug hufy huf ghdrsuytivv tdrdiuyg fytdutfiuygfoyug disastrous loves, and crushing losses.",
    "publishDate": "October 18, 2022",
    "publisher": "HarperCollins",
    "language": "English",
    "subjects": "Literary Fiction, Contemporary",
},
{
    "id": "77",
    "product": "Top Rated",
    "image": "images/topratedbooks/img1.jpg",
    "title": "House of Flame and Shadow",
    "author": "Sarah J. Maas",
    "price": "299",
    "category": "Fiction/Fantacy",
    "description": "Bryce Quinlan never expected to see a world other than Midgard, but now that she has, all she wants is to get back. Everything she loves is in Midgard: her family, her friends, her mate. Stranded in a strange new world, she's going to need all her wits about her to get home again. And that's no easy feat when she has no idea who to trust.",
    "publishDate": "2024",
    "publisher": "Bloomsbury USA",
    "language": "",
    "subjects": "Fiction/Fantacy/Epic"
},
{
    "id": "78",
    "product": "Top Rated",
    "image": "images/topratedbooks/img2.jpg",
    "title": "The Wager",
    "author": "David Grann",
    "price": "769",
    "category": "History",
    "description": "'The beauty of The Wager unfurls like a great sail... one of the finest nonfiction books I’ve ever read' Guardian ‘The greatest sea story ever told’ Spectator ‘A cracking yarn… Grann’s taste for desperate predicaments finds its fullest expression here’ ObserverFrom the international bestselling author of KILLERS OF THE FLOWER MOON and THE LOST CITY OF Z, a mesmerising story of shipwreck, mutiny and murder, culminating in a court martial that reveals a shocking truth.",
    "publishDate": "11 May 2023",
    "publisher": "Simon & Schuster UK",
    "language": "English",
    "subjects": "History / Military / Naval, Transportation / Ships & Shipbuilding / History, Mutiny -- Great Britain, Shipwreck victims -- Patagonia (Argentina and Chile) -- Great Britain, Shipwrecks -- Patagonia (Argentina and Chile)"
},
{
    "id": "79",
    "product": "Top Rated",
    "image": "images/topratedbooks/img3.jpg",
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "price": "",
    "category": "Romance novel",
    "description": "Bryce Quinlan never expected to see a world other than Midgard, but now that she has, all she wants is to get back. Everything she loves is in Midgard: her family, her friends, her mate. Stranded in a strange new world, she's going to need all her wits about her to get home again. And that's no easy feat when she has no idea who to trust.",
    "publishDate": "28 January 1813",
    "publisher": "T. Egerton, Whitehall",
    "language": "English",
    "subjects": "A novel of manners, it follows the character development of Elizabeth Bennet, the protagonist of the book, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.Classic Regency novel Romance novel",
},
{
        "id": "80",
        "product": "Top Rated",
        "image": "images/topratedbooks/img4.jpg",
        "title": "Nineteen Eighty-Four",
        "author": "George Orwell ",
        "price": "",
        "category": "Dystopian",
        "description": "George Orwell wrote 1984 to teach people a lesson about the negative things that could happen if they allowed their government to exercise total control. The totalitarian regime of Oceania is able to manipulate their citizens into believing anything, which allows them as much power as they could possibly want.",
        "publishDate": "8 June 1949",
        "publisher": "Secker & Warburg",
        "language": "English",
        "subjects": "Dystopian/political fiction/social science fiction" 
},
{
    "id": "81",
    "product": "New York Times Bestsellers",
    "image": "images/nytimebooks/img1.jpg",
    "title": "The Covenant of Water",
    "author": "Abraham Verghese",
    "price": "299",
    "category": "Fiction",
    "description": "A sweeping family saga set in Kerala, India, spanning over a century. The novel follows three generations of a family dealing with medical and personal challenges against the backdrop of India's social changes.",
    "publishDate": "June 6, 2023",
    "publisher": "Grove Atlantic",
    "language": "English",
    "subjects": "Literary Fiction, Historical Fiction",
},
{
    "id": "82",
    "product": "New York Times Bestsellers",
    "image": "images/nytimebooks/img2.png",
    "title": "Hello Beautiful",
    "author": "Ann Napolitano",
    "price": "269",
    "category": "Fiction",
    "description": "A contemporary novel that explores the life of a man who falls in love with a woman from a large, close-knit family. The story delves into themes of love, family, and personal growth.",
    "publishDate": "March 14, 2023",
    "publisher": "Penguin Random House",
    "language": "English",
    "subjects": "Literary Fiction, Contemporary Fiction",
},
{
    "id": "83",
    "product": "New York Times Bestsellers",
    "image": "images/nytimebooks/img3.jpg",
    "title": "The 6:20 Man",
    "author": "David Baldacci",
    "price": "269",
    "category": "Fiction",
    "description": "A thriller that follows a man who uncovers a complex conspiracy involving his former employer and must navigate danger to uncover the truth. It combines suspense with intricate plotting.",
    "publishDate": "July 11, 2023",
    "publisher": "Grand Central Publishing",
    "language": "English",
    "subjects": "Thriller, Mystery",
},
{
    "id": "84",
    "product": "New York Times Bestsellers",
    "image": "images/nytimebooks/img4.jpg",
    "title": "Pineapple Street",
    "author": "Jenny Jackson",
    "price": "269",
    "category": "Fiction",
    "description": "A novel centered around the wealthy and complex lives of the Stockton family in Brooklyn. The story delves into themes of privilege, family dynamics, and personal identity.",
    "publishDate": "July 11, 2023",
    "publisher": "Knopf",
    "language": "English",
    "subjects": "Contemporary Fiction, Family Saga",
},
{
    "id": "85",
    "product": "New York Times Bestsellers",
    "image": "images/nytimebooks/img5.jpg",
    "title": "Matthew Quirk",
    "author": "David Baldacci",
    "price": "269",
    "category": "Fiction",
    "description": "A high-stakes thriller involving a low-level FBI agent who gets entangled in a dangerous conspiracy with international implications. The novel is fast-paced and filled with suspense.",
    "publishDate": "April 11, 2023",
    "publisher": "William Morrow",
    "language": "English",
    "subjects": "Thriller, Suspense",
}
]
